### ISSUE TITLE
Shorten URLs

### ISSUE THREAD

**Issue by mrclay** [hypeJunction/Elgg-proxy#1]
Use HMAC with MD5 (MD5 is still completely safe in HMAC), and encode using [Base64URL encoding](https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/Security/Hmac.php#L57).

Create the URL like:

``` php
"mod/proxy/e{$expires}/a{$access_id}/l{$mtime}/d{$disposition}/$mac/path/to/file.gif"
```

Where $disposition is "i" or "a".

Parsing:

``` php
if (preg_match('~/e(\d+)/a(\d+)/l(\d+)/d([ia])/([a-zA-Z0-9\-_]+)/(.*)$~', $uri, $m)) {
   list(, $expires, $access_id, $last_updated, $disposition, $mac, $path) = $m;
}
```

**Comment by hypeJunction** [comment]
:sweat_smile: Will do

**Comment by hypeJunction** [comment]
Resulting URL:

`https://hj.dev/mod/proxy/e0/a0/l1447268209/di/kc/KMlO-oRuC9q-9Bepu6zYRKYAPJLEp2e2-SaFXQm1oL4/1/43/ads/1447268210giphy.gif`
