### ISSUE TITLE
is it only for elgg2.0.x?

### ISSUE THREAD

**Issue by abukaab** [hypeJunction/Elgg-proxy#2]
I want to use this plugin in my elgg2.3 installation.
But, I couldn't do it, because of 
`	<requires>
		<type>elgg_release</type>
		<version>2.1</version>
		<comparison>lt</comparison>
	</requires>`
in manifest.xml

Any idea, how to use this plugin for elgg2.3?

Thanks,
Prase Tyo

**Comment by hypeJunction** [comment]
The concepts implemented in this plugin have been added to core, so you don't need this plugin in later versions
